HanHwa-Team1-Final-Project/MOIM-FE

src/pages/event/EventDialog.vue
* #27 
- 기본 일정 등록
- 알림 설정 추가
- 반복 설정 추가
- todolist 추가
=> 일정 등록 api 연동

src/pages/event/EventDialog.vue
=> 주별, 일별 캘린더 드래그 - 일정생성 시 시간 적용

src/App.vue, src/components/layout/AppSideBar.vue, src/pages/moim/MoimDialog.vue
=> 모임, 일정 dialog충돌 해결

src/components/UpdateEvent.vue, src/components/layout/AppSideBar.vue, src/pages/search/EventDetail.vue, src/views/FullCalendarComponent.vue
- 간단한 내용으로 인해 따로 이슈 생성 없이 진행함
- 현재 백엔드에 있는 일정 생성 API에 맞게 관련된 update 기능을 생성함
- 추후 백엔드 API 수정과 함께 추가 기능 제공 예정
=> 일정 수정 기능 완성

src/pages/moim/MoimDetail.vue
=> 게스트 - 모임 수락/거부 요청

src/components/MainPage.vue, src/components/layout/AppHeader.vue, src/pages/event/EventDialog.vue, src/pages/moim/MoimDetail.vue, src/pages/moim/MoimDialog.vue, src/router/index.js, src/views/FullCalendarComponent.vue
일정 등록 취소 시 데이터 초기화, 모임 알림 타입에 따라 dialog 변경, 추천 일정 조회 및 확정 api 연동
=> 모임, 일정 관련 수정

src/components/layout/AppHeader.vue, src/pages/moim/MoimDetail.vue
=> 호스트 추천일정 선택 추가

src/components/layout/AppHeader.vue, src/pages/moim/MoimDetail.vue, src/pages/moim/MoimDialog.vue
=> 모임 확정 - 게스트, 호스트 알림 - 확정일정 확인

src/components/layout/AppSideBar.vue, src/pages/moim/MoimDialog.vue, src/pages/myPage/MyPageDialog.vue
마이페이지 조회기능만 추가함,
수정기능은 추후에 하기로 함
=> 마이페이지 조회 기능 추가

src/pages/event/EventDialog.vue, src/pages/moim/MoimDetail.vue, src/views/FullCalendarComponent.vue
=> 모임 확정 후 일정등록

src/pages/moim/MoimList.vue, src/pages/myPage/MyPageDialog.vue
=> 마이페이지 수정, 다이얼로그 계속 뜨는거 수정

src/components/UpdateEvent.vue, src/components/layout/AppHeader.vue, src/components/layout/AppSideBar.vue, src/pages/eisenhower/EisenhowerMatrix.vue, src/pages/event/EventDetailDialog.vue, src/pages/event/EventDialog.vue, src/pages/search/DeleteRepeatEvent.vue, src/pages/search/EventDetail.vue, src/pages/search/SearchResults.vue, src/views/FullCalendarComponent.vue
* #73 
- 로그아웃
- 일정상세 맞춤(검색, 캘린더)
- 아이젠하워 사분면으로 변경
- 일정 색상 중요도에 따라 변경
=> 로그아웃 및 디자인 수정

src/pages/moim/MoimList.vue
=> 모임 리스트 페이징 기능 추가

src/pages/moim/MoimList.vue
=> 모임 리스트 수정/ 모임 리스트 없을 시 "모임이 없습니다" 문구만 나오게 수정

src/pages/event/EventDetailDialog.vue, src/pages/search/EventDetail.vue
=> todolist 체크 변경

src/pages/moim/MoimList.vue
=> 모임리스트 디자인 수정,확정 시 일정 등록 수정

src/components/layout/AppHeader.vue, src/components/layout/AppSideBar.vue, src/pages/chat/ChatDialog.vue, src/router/index.js
=> 채팅방 생성 및 실시간 알림

src/components/layout/AppHeader.vue, src/pages/chat/ChatDialog.vue, src/pages/event/EventDetailDialog.vue, src/pages/moim/MoimDetail.vue, src/pages/search/EventDetail.vue, src/views/FullCalendarComponent.vue
=> 채팅방 생성 api 연결

src/components/layout/AppSideBar.vue, src/pages/moim/MoimList.vue
=> 모임 생성 사이드바에서 제거 후 모임 리스트에 추가

.env
=> baseurl 변경

.github/workflows/deploy_frontend_with_s3.yaml
=> aws credential 버전 업

.github/workflows/deploy_frontend_with_s3.yaml
=> aws secretkey 수정

src/components/layout/AppHeader.vue
=> sse uri 변경

src/components/layout/AppSideBar.vue, src/pages/moim/MoimList.vue, src/utils/date-utils.js
=> 오늘의 일정 기능 추가

src/components/layout/AppSideBar.vue
=> [Fix] 충돌 해결

src/components/layout/AppSideBar.vue, src/pages/chat/ChattingList.vue
=> [Fix] 채팅 관련 디자인 수정

src/components/layout/AppSideBar.vue, src/pages/chat/ChattingList.vue, src/pages/moim/MoimList.vue
=> [Refactor] 디자인 수정

src/components/layout/AppHeader.vue, src/pages/event/EventDialog.vue, src/pages/moim/MoimList.vue, src/pages/search/SearchResults.vue, src/stores/notificationStore.js, src/stores/searchStore.js
=> 검색리스트 변경 및 알림 목록 삭제

src/components/UpdateEvent.vue, src/pages/event/EventDialog.vue
=> 일정등록, 수정 rule 추가
